CREATE TABLE IF NOT EXISTS ZipCodes(
        ZipCodeID INT(5) UNSIGNED NOT NULL,
        StateID VARCHAR(2) NOT NULL,
        City VARCHAR(255) NOT NULL, 
        Time_Stamp DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (StateID) REFERENCES States(StateID), 
    PRIMARY KEY (ZipCodeID)
);

INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93242,'CA','Laton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93611,'CA','Clovis',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93309,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91340,'CA','San Fernando',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91750,'CA','La Verne',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91016,'CA','Monrovia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93901,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93907,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93926,'CA','Gonzales',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90620,'CA','Buena Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92704,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92806,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92701,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92373,'CA','Redlands',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92405,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93433,'CA','Grover Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93111,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93292,'CA','Visalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93030,'CA','Oxnard',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93001,'CA','Ventura',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93725,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93706,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93624,'CA','Five Points',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93301,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93263,'CA','Shafter',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93206,'CA','Buttonwillow',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90065,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91706,'CA','Baldwin Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90680,'CA','Stanton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92807,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91710,'CA','Chino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93291,'CA','Visalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93033,'CA','Oxnard',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93646,'CA','Orange Cove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93662,'CA','Selma',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93619,'CA','Clovis',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92887,'CA','Yorba Linda',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93272,'CA','Tipton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93656,'CA','Riverdale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92651,'CA','Laguna Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92708,'CA','Fountain Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91362,'CA','Thousand Oaks',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93230,'CA','Hanford',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92308,'CA','Apple Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92630,'CA','Lake Forest',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91702,'CA','Azusa',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90280,'CA','South Gate',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91762,'CA','Ontario',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93308,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92711,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93612,'CA','Clovis',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93274,'CA','Tulare',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92860,'CA','Norco',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93908,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91352,'CA','Sun Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93060,'CA','Santa Paula',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93906,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91361,'CA','Westlake Village',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93210,'CA','Coalinga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93212,'CA','Corcoran',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91775,'CA','San Gabriel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91746,'CA','La Puente',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92345,'CA','Hesperia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92399,'CA','Yucaipa',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93117,'CA','Goleta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93924,'CA','Carmel Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91331,'CA','Pacoima',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93930,'CA','King City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92865,'CA','Orange',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92688,'CA','Rancho Santa Margari',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93380,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93312,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92590,'CA','Temecula',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93654,'CA','Reedley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93668,'CA','Tranquillity',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95023,'CA','Hollister',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92311,'CA','Barstow',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93270,'CA','Terra Bella',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93703,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92365,'CA','Newberry Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93290,'CA','Visalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93004,'CA','Ventura',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92883,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93630,'CA','Kerman',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93960,'CA','Soledad',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91324,'CA','Northridge',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92581,'CA','San Jacinto',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91766,'CA','Pomona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93711,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93637,'CA','Madera',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90638,'CA','La Mirada',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93631,'CA','Kingsburg',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93454,'CA','Santa Maria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92371,'CA','Phelan',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92886,'CA','Yorba Linda',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93622,'CA','Firebaugh',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92646,'CA','Huntington Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93204,'CA','Avenal',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93314,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93401,'CA','San Luis Obispo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92606,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93250,'CA','Mcfarland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92223,'CA','Beaumont',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92570,'CA','Perris',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93010,'CA','Camarillo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93307,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92507,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92337,'CA','Fontana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93610,'CA','Chowchilla',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93514,'CA','Bishop',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90077,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92324,'CA','Colton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Mira Loma',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92869,'CA','Orange',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92801,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93551,'CA','Palmdale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91803,'CA','Alhambra',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92501,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90723,'CA','Paramount',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93420,'CA','Arroyo Grande',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92382,'CA','Running Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92562,'CA','Murrieta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93257,'CA','Porterville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90755,'CA','Signal Hill',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92315,'CA','Big Bear Lake',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90211,'CA','Beverly Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92374,'CA','Redlands',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92377,'CA','Rialto',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92335,'CA','Fontana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91020,'CA','Montrose',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91770,'CA','Rosemead',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93645,'CA','O Neals',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93221,'CA','Exeter',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93003,'CA','Ventura',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93061,'CA','Santa Paula',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90660,'CA','Pico Rivera',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93266,'CA','Stratford',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93203,'CA','Arvin',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91007,'CA','Arcadia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92592,'CA','Temecula',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93705,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93723,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93247,'CA','Lindsay',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93305,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93306,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93021,'CA','Moorpark',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92530,'CA','Lake Elsinore',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93636,'CA','Madera',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93232,'CA','Hanford',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92878,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93463,'CA','Solvang',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93609,'CA','Caruthers',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92879,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93065,'CA','Simi Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92880,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91301,'CA','Agoura Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92563,'CA','Murrieta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93280,'CA','Wasco',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93446,'CA','Paso Robles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91740,'CA','Glendora',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93015,'CA','Fillmore',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90040,'CA','Commerce',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93422,'CA','Atascadero',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93614,'CA','Coarsegold',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92274,'CA','Thermal',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93063,'CA','Simi Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93653,'CA','Raymond',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93277,'CA','Visalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93534,'CA','Lancaster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90731,'CA','San Pedro',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93456,'CA','Santa Maria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93625,'CA','Fowler',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92705,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92346,'CA','Highland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93461,'CA','Shandon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93101,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93458,'CA','Santa Maria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93455,'CA','Santa Maria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93313,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93215,'CA','Delano',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92673,'CA','San Clemente',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92544,'CA','Hemet',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93933,'CA','Marina',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91786,'CA','Upland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93267,'CA','Strathmore',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93444,'CA','Nipomo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91423,'CA','Sherman Oaks',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93657,'CA','Sanger',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93234,'CA','Huron',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93434,'CA','Guadalupe',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91709,'CA','Chino Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93640,'CA','Mendota',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91302,'CA','Calabasas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90247,'CA','Gardena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93722,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92284,'CA','Yucca Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92805,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93618,'CA','Dinuba',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93110,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92509,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91350,'CA','Santa Clarita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91773,'CA','San Dimas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91730,'CA','Rancho Cucamonga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93275,'CA','Tulare',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93245,'CA','Lemoore',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92868,'CA','Orange',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92703,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92867,'CA','Orange',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Eastvale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91355,'CA','Valencia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90631,'CA','La Habra',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93553,'CA','Pearblossom',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92821,'CA','Brea',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92503,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93013,'CA','Carpinteria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92663,'CA','Newport Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93660,'CA','San Joaquin',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91768,'CA','Pomona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93777,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92808,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92412,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93405,'CA','San Luis Obispo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93902,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95045,'CA','San Juan Bautista',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90222,'CA','Compton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92236,'CA','Coachella',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92831,'CA','Fullerton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90221,'CA','Rancho Dominguez',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93730,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90650,'CA','Norwalk',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92596,'CA','Winchester',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92301,'CA','Adelanto',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92832,'CA','Fullerton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93031,'CA','Oxnard',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93256,'CA','Pixley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93460,'CA','Santa Ynez',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92555,'CA','Moreno Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92692,'CA','Mission Viejo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93727,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93905,'CA','Salinas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92201,'CA','Indio',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93311,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92203,'CA','Bermuda Dunes',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92595,'CA','Wildomar',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92660,'CA','Newport Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93616,'CA','Del Rey',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92504,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93302,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92648,'CA','Huntington Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93436,'CA','Lompoc',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92316,'CA','Bloomington',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91723,'CA','Covina',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91411,'CA','Van Nuys',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91360,'CA','Thousand Oaks',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93426,'CA','Bradley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90808,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91701,'CA','Alta Loma',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92571,'CA','Perris',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92260,'CA','Palm Desert',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91765,'CA','Diamond Bar',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92313,'CA','Grand Terrace',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93505,'CA','California City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90290,'CA','Topanga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92618,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92307,'CA','Apple Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93432,'CA','Creston',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93535,'CA','Lancaster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92225,'CA','Blythe',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93108,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93652,'CA','Raisin City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90221,'CA','Compton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92347,'CA','Hinkley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92881,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91764,'CA','Ontario',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93613,'CA','Clovis',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91701,'CA','Rancho Cucamonga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93023,'CA','Ojai',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91436,'CA','Encino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90744,'CA','Wilmington',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91722,'CA','Covina',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92506,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90405,'CA','Santa Monica',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93105,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91748,'CA','Rowland Heights',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92653,'CA','Laguna Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91731,'CA','El Monte',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93561,'CA','Tehachapi',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93036,'CA','Oxnard',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93532,'CA','Lake Hughes',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91390,'CA','Santa Clarita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92840,'CA','Garden Grove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90262,'CA','Lynwood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90807,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92545,'CA','Hemet',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90301,'CA','Inglewood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93002,'CA','Ventura',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91107,'CA','Pasadena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93445,'CA','Oceano',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90245,'CA','El Segundo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90706,'CA','Bellflower',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91006,'CA','Arcadia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93402,'CA','Los Osos',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91724,'CA','Covina',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92415,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93704,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92407,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92861,'CA','Villa Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92584,'CA','Menifee',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93728,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92677,'CA','Laguna Niguel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91761,'CA','Ontario',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93465,'CA','Templeton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92505,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92626,'CA','Costa Mesa',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90064,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93227,'CA','Goshen',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90501,'CA','Torrance',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90304,'CA','Inglewood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91390,'CA','Agua Dulce',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90049,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91351,'CA','Santa Clarita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91364,'CA','Woodland Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91321,'CA','Newhall',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90606,'CA','Whittier',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93442,'CA','Morro Bay',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93927,'CA','Greenfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93261,'CA','Richgrove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93441,'CA','Los Olivos',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95004,'CA','Aromas',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92602,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93539,'CA','Lancaster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93283,'CA','Weldon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92359,'CA','Mentone',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90042,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92240,'CA','Desert Hot Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93022,'CA','Oak View',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91040,'CA','Sunland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92553,'CA','Moreno Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91505,'CA','Burbank',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90254,'CA','Hermosa Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93451,'CA','San Miguel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91320,'CA','Newbury Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91402,'CA','Panorama City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92268,'CA','Pioneertown',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91342,'CA','Sylmar',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92586,'CA','Menifee',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91344,'CA','Granada Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91381,'CA','Stevenson Ranch',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92211,'CA','Palm Desert',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92372,'CA','Pinon Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90033,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93920,'CA','Big Sur',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92870,'CA','Placentia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92843,'CA','Garden Grove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92649,'CA','Huntington Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93923,'CA','Carmel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91767,'CA','Pomona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92675,'CA','San Juan Capistrano',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93552,'CA','Palmdale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93483,'CA','Grover Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93202,'CA','Armona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93244,'CA','Lemon Cove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92223,'CA','Cherry Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90241,'CA','Downey',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92203,'CA','Indio',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91741,'CA','Glendora',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93940,'CA','Monterey',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93428,'CA','Cambria',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92780,'CA','Tustin',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95043,'CA','Paicines',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90067,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92629,'CA','Dana Point',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95012,'CA','Castroville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93453,'CA','Santa Margarita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91331,'CA','Arleta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93513,'CA','Big Pine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91406,'CA','Van Nuys',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93066,'CA','Somis',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93627,'CA','Helm',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90703,'CA','Cerritos',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92867,'CA','Villa Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90717,'CA','Lomita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92253,'CA','La Quinta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93601,'CA','Ahwahnee',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93216,'CA','Delano',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92614,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91321,'CA','Santa Clarita',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92835,'CA','Fullerton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90058,'CA','Vernon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91367,'CA','Woodland Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92585,'CA','Menifee',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93606,'CA','Biola',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91303,'CA','Canoga Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93117,'CA','Gaviota',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90021,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92672,'CA','San Clemente',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90034,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93240,'CA','Lake Isabella',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91784,'CA','Upland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91325,'CA','Northridge',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90712,'CA','Lakewood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93720,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91733,'CA','South El Monte',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93450,'CA','San Ardo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91204,'CA','Glendale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90631,'CA','La Habra Heights',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92270,'CA','Rancho Mirage',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92882,'CA','Corona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93007,'CA','Ventura',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93604,'CA','Bass Lake',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92344,'CA','Hesperia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92397,'CA','Wrightwood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90272,'CA','Pacific Palisades',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91326,'CA','Porter Ranch',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92395,'CA','Victorville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93447,'CA','Paso Robles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93258,'CA','Porterville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90640,'CA','Montebello',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92833,'CA','Fullerton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90240,'CA','Downey',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90274,'CA','Rolling Hills Estate',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92352,'CA','Lake Arrowhead',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93449,'CA','Pismo Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93638,'CA','Madera',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90249,'CA','Gardena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92647,'CA','Huntington Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91744,'CA','La Puente',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92564,'CA','Murrieta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90277,'CA','Redondo Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90502,'CA','Torrance',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93012,'CA','Camarillo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93721,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92320,'CA','Calimesa',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91606,'CA','North Hollywood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92625,'CA','Corona Del Mar',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91106,'CA','Pasadena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90505,'CA','Torrance',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90802,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92532,'CA','Lake Elsinore',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90250,'CA','Hawthorne',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92508,'CA','Riverside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92841,'CA','Garden Grove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91706,'CA','Irwindale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92802,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93648,'CA','Parlier',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93201,'CA','Alpaugh',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91307,'CA','Bell Canyon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93510,'CA','Acton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92536,'CA','Aguanga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92356,'CA','Lucerne Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92678,'CA','Trabuco Canyon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90746,'CA','Carson',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91739,'CA','Rancho Cucamonga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90670,'CA','Santa Fe Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90023,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92248,'CA','La Quinta',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90201,'CA','Bell Gardens',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90018,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90805,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90403,'CA','Santa Monica',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92276,'CA','Thousand Palms',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92408,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93701,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90260,'CA','Lawndale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93108,'CA','Montecito',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93406,'CA','San Luis Obispo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92543,'CA','Hemet',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90248,'CA','Gardena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91708,'CA','Chino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91335,'CA','Reseda',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91790,'CA','West Covina',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91354,'CA','Valencia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91732,'CA','El Monte',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92807,'CA','Anaheim Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92226,'CA','Blythe',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91040,'CA','Shadow Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90806,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91406,'CA','Lake Balboa',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90745,'CA','Carson',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92624,'CA','Capistrano Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93020,'CA','Moorpark',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95039,'CA','Moss Landing',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92615,'CA','Huntington Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91311,'CA','Chatsworth',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91384,'CA','Castaic',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93421,'CA','Arroyo Grande',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90713,'CA','Lakewood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92252,'CA','Joshua Tree',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92735,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93581,'CA','Tehachapi',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92385,'CA','Skyforest',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90710,'CA','Harbor City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91201,'CA','Glendale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93502,'CA','Mojave',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Jurupa Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92310,'CA','Fort Irwin',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93639,'CA','Madera',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92586,'CA','Sun City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93651,'CA','Prather',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93390,'CA','Bakersfield',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92607,'CA','Laguna Niguel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92866,'CA','Orange',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90815,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93279,'CA','Visalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93238,'CA','Kernville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92549,'CA','Idyllwild',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93550,'CA','Palmdale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93219,'CA','Earlimart',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93602,'CA','Auberry',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93664,'CA','Shaver Lake',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90701,'CA','Artesia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91316,'CA','Encino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93637,'CA','Berenda',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92220,'CA','Banning',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91221,'CA','Glendale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93907,'CA','Prunedale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91104,'CA','Pasadena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92728,'CA','Fountain Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93591,'CA','Palmdale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93041,'CA','Port Hueneme',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93667,'CA','Tollhouse',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91343,'CA','North Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91711,'CA','Claremont',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92683,'CA','Westminster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92591,'CA','Temecula',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93921,'CA','Carmel',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92654,'CA','Laguna Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90046,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93709,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93440,'CA','Los Alamos',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91763,'CA','Montclair',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93255,'CA','Onyx',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92285,'CA','Landers',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92539,'CA','Anza',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93675,'CA','Squaw Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93518,'CA','Caliente',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92604,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93555,'CA','Ridgecrest',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93205,'CA','Bodfish',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92612,'CA','Irvine',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90602,'CA','Whittier',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92202,'CA','Indio',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (95024,'CA','Hollister',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92344,'CA','Oak Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93644,'CA','Oakhurst',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93455,'CA','Orcutt',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90212,'CA','Beverly Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93403,'CA','San Luis Obispo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90026,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92567,'CA','Nuevo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93536,'CA','Lancaster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91362,'CA','Westlake Village',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93950,'CA','Pacific Grove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92691,'CA','Mission Viejo',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90071,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92585,'CA','Romoland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90732,'CA','San Pedro',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93012,'CA','Santa Rosa Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93925,'CA','Chualar',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90274,'CA','Rolling Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91766,'CA','Phillips Ranch',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91353,'CA','Sun Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93531,'CA','Keene',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92375,'CA','Redlands',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92264,'CA','Palm Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91342,'CA','Lake View Terrace',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92258,'CA','North Palm Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93543,'CA','Littlerock',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92392,'CA','Victorville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91745,'CA','Hacienda Heights',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93726,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90503,'CA','Torrance',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93249,'CA','Lost Hills',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90504,'CA','Torrance',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93647,'CA','Orosi',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91042,'CA','Tujunga',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90017,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92676,'CA','Silverado',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92342,'CA','Helendale',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93427,'CA','Buellton',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91351,'CA','Canyon Country',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92842,'CA','Garden Grove',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90715,'CA','Lakewood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93103,'CA','Santa Barbara',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90402,'CA','Santa Monica',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92707,'CA','Santa Ana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92256,'CA','Morongo Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93560,'CA','Rosamond',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90265,'CA','Malibu',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92336,'CA','Fontana',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93286,'CA','Woodlake',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92339,'CA','Forest Falls',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93702,'CA','Fresno',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93524,'CA','Edwards',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93562,'CA','Trona',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92661,'CA','Newport Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91306,'CA','Winnetka',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93243,'CA','Lebec',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92423,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90803,'CA','Long Beach',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92679,'CA','Trabuco Canyon',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93429,'CA','Casmalia',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92694,'CA','Ladera Ranch',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90046,'CA','West Hollywood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92548,'CA','Homeland',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92509,'CA','Jurupa Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90048,'CA','West Hollywood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92314,'CA','Big Bear City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91320,'CA','Thousand Oaks',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93584,'CA','Lancaster',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91401,'CA','Van Nuys',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91030,'CA','South Pasadena',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92804,'CA','Anaheim',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90069,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90255,'CA','Huntington Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90230,'CA','Culver City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91789,'CA','Walnut',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90604,'CA','Whittier',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93430,'CA','Cayucos',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90621,'CA','Buena Park',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90275,'CA','Rancho Palos Verdes',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92277,'CA','Twentynine Palms',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93464,'CA','Solvang',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92557,'CA','Moreno Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92551,'CA','Moreno Valley',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93643,'CA','North Fork',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93265,'CA','Springville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92241,'CA','Desert Hot Springs',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93932,'CA','Lockwood',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92234,'CA','Cathedral City',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (90044,'CA','Los Angeles',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93271,'CA','Three Rivers',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (93955,'CA','Seaside',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92393,'CA','Victorville',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (92410,'CA','San Bernardino',NULL);
INSERT INTO mytable(ZipCodeID,StateID,City,Time_Stamp) VALUES (91791,'CA','West Covina',NULL);
