USE schemers;

CREATE TABLE IF NOT EXISTS ZipCodes(
        ZipCodeID INT(5) UNSIGNED NOT NULL,
        StateID VARCHAR(2) NOT NULL,
        City VARCHAR(255) NOT NULL, 
        Time_Stamp DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (StateID) REFERENCES States(StateID), 
    PRIMARY KEY (ZipCodeID)
);

INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93242,'CA','Laton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93611,'CA','Clovis',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93309,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91340,'CA','San Fernando',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91750,'CA','La Verne',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91016,'CA','Monrovia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93901,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93907,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93926,'CA','Gonzales',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90620,'CA','Buena Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92704,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92806,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92701,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92373,'CA','Redlands',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92405,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93433,'CA','Grover Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93111,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93292,'CA','Visalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93030,'CA','Oxnard',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93001,'CA','Ventura',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93725,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93706,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93624,'CA','Five Points',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93301,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93263,'CA','Shafter',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93206,'CA','Buttonwillow',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90065,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91706,'CA','Baldwin Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90680,'CA','Stanton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92807,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91710,'CA','Chino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93291,'CA','Visalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93033,'CA','Oxnard',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93646,'CA','Orange Cove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93662,'CA','Selma',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93619,'CA','Clovis',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92887,'CA','Yorba Linda',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93272,'CA','Tipton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93656,'CA','Riverdale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92651,'CA','Laguna Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92708,'CA','Fountain Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91362,'CA','Thousand Oaks',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93230,'CA','Hanford',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92308,'CA','Apple Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92630,'CA','Lake Forest',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91702,'CA','Azusa',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90280,'CA','South Gate',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91762,'CA','Ontario',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93308,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92711,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93612,'CA','Clovis',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93274,'CA','Tulare',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92860,'CA','Norco',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93908,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91352,'CA','Sun Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93060,'CA','Santa Paula',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93906,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91361,'CA','Westlake Village',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93210,'CA','Coalinga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93212,'CA','Corcoran',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91775,'CA','San Gabriel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91746,'CA','La Puente',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92345,'CA','Hesperia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92399,'CA','Yucaipa',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93117,'CA','Goleta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93924,'CA','Carmel Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91331,'CA','Pacoima',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93930,'CA','King City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92865,'CA','Orange',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92688,'CA','Rancho Santa Margari',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93380,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93312,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92590,'CA','Temecula',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93654,'CA','Reedley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93668,'CA','Tranquillity',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95023,'CA','Hollister',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92311,'CA','Barstow',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93270,'CA','Terra Bella',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93703,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92365,'CA','Newberry Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93290,'CA','Visalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93004,'CA','Ventura',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92883,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93630,'CA','Kerman',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93960,'CA','Soledad',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91324,'CA','Northridge',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92581,'CA','San Jacinto',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91766,'CA','Pomona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93711,'CA','Fresno',NOW());
/*INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93637,'CA','Madera',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90638,'CA','La Mirada',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93631,'CA','Kingsburg',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93454,'CA','Santa Maria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92371,'CA','Phelan',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92886,'CA','Yorba Linda',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93622,'CA','Firebaugh',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92646,'CA','Huntington Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93204,'CA','Avenal',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93314,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93401,'CA','San Luis Obispo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92606,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93250,'CA','Mcfarland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92223,'CA','Beaumont',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92570,'CA','Perris',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93010,'CA','Camarillo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93307,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92507,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92337,'CA','Fontana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93610,'CA','Chowchilla',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93514,'CA','Bishop',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90077,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92324,'CA','Colton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Mira Loma',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92869,'CA','Orange',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92801,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93551,'CA','Palmdale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91803,'CA','Alhambra',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92501,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90723,'CA','Paramount',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93420,'CA','Arroyo Grande',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92382,'CA','Running Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92562,'CA','Murrieta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93257,'CA','Porterville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90755,'CA','Signal Hill',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92315,'CA','Big Bear Lake',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90211,'CA','Beverly Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92374,'CA','Redlands',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92377,'CA','Rialto',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92335,'CA','Fontana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91020,'CA','Montrose',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91770,'CA','Rosemead',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93645,'CA','O Neals',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93221,'CA','Exeter',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93003,'CA','Ventura',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93061,'CA','Santa Paula',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90660,'CA','Pico Rivera',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93266,'CA','Stratford',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93203,'CA','Arvin',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91007,'CA','Arcadia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92592,'CA','Temecula',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93705,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93723,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93247,'CA','Lindsay',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93305,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93306,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93021,'CA','Moorpark',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92530,'CA','Lake Elsinore',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93636,'CA','Madera',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93232,'CA','Hanford',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92878,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93463,'CA','Solvang',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93609,'CA','Caruthers',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92879,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93065,'CA','Simi Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92880,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91301,'CA','Agoura Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92563,'CA','Murrieta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93280,'CA','Wasco',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93446,'CA','Paso Robles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91740,'CA','Glendora',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93015,'CA','Fillmore',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90040,'CA','Commerce',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93422,'CA','Atascadero',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93614,'CA','Coarsegold',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92274,'CA','Thermal',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93063,'CA','Simi Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93653,'CA','Raymond',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93277,'CA','Visalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93534,'CA','Lancaster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90731,'CA','San Pedro',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93456,'CA','Santa Maria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93625,'CA','Fowler',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92705,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92346,'CA','Highland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93461,'CA','Shandon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93101,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93458,'CA','Santa Maria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93455,'CA','Santa Maria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93313,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93215,'CA','Delano',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92673,'CA','San Clemente',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92544,'CA','Hemet',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93933,'CA','Marina',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91786,'CA','Upland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93267,'CA','Strathmore',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93444,'CA','Nipomo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91423,'CA','Sherman Oaks',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93657,'CA','Sanger',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93234,'CA','Huron',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93434,'CA','Guadalupe',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91709,'CA','Chino Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93640,'CA','Mendota',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91302,'CA','Calabasas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90247,'CA','Gardena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93722,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92284,'CA','Yucca Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92805,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93618,'CA','Dinuba',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93110,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92509,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91350,'CA','Santa Clarita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91773,'CA','San Dimas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91730,'CA','Rancho Cucamonga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93275,'CA','Tulare',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93245,'CA','Lemoore',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92868,'CA','Orange',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92703,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92867,'CA','Orange',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Eastvale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91355,'CA','Valencia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90631,'CA','La Habra',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93553,'CA','Pearblossom',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92821,'CA','Brea',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92503,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93013,'CA','Carpinteria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92663,'CA','Newport Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93660,'CA','San Joaquin',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91768,'CA','Pomona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93777,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92808,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92412,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93405,'CA','San Luis Obispo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93902,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95045,'CA','San Juan Bautista',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90222,'CA','Compton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92236,'CA','Coachella',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92831,'CA','Fullerton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90221,'CA','Rancho Dominguez',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93730,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90650,'CA','Norwalk',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92596,'CA','Winchester',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92301,'CA','Adelanto',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92832,'CA','Fullerton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93031,'CA','Oxnard',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93256,'CA','Pixley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93460,'CA','Santa Ynez',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92555,'CA','Moreno Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92692,'CA','Mission Viejo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93727,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93905,'CA','Salinas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92201,'CA','Indio',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93311,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92203,'CA','Bermuda Dunes',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92595,'CA','Wildomar',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92660,'CA','Newport Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93616,'CA','Del Rey',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92504,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93302,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92648,'CA','Huntington Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93436,'CA','Lompoc',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92316,'CA','Bloomington',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91723,'CA','Covina',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91411,'CA','Van Nuys',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91360,'CA','Thousand Oaks',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93426,'CA','Bradley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90808,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91701,'CA','Alta Loma',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92571,'CA','Perris',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92260,'CA','Palm Desert',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91765,'CA','Diamond Bar',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92313,'CA','Grand Terrace',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93505,'CA','California City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90290,'CA','Topanga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92618,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92307,'CA','Apple Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93432,'CA','Creston',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93535,'CA','Lancaster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92225,'CA','Blythe',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93108,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93652,'CA','Raisin City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90221,'CA','Compton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92347,'CA','Hinkley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92881,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91764,'CA','Ontario',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93613,'CA','Clovis',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91701,'CA','Rancho Cucamonga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93023,'CA','Ojai',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91436,'CA','Encino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90744,'CA','Wilmington',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91722,'CA','Covina',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92506,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90405,'CA','Santa Monica',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93105,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91748,'CA','Rowland Heights',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92653,'CA','Laguna Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91731,'CA','El Monte',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93561,'CA','Tehachapi',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93036,'CA','Oxnard',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93532,'CA','Lake Hughes',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91390,'CA','Santa Clarita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92840,'CA','Garden Grove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90262,'CA','Lynwood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90807,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92545,'CA','Hemet',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90301,'CA','Inglewood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93002,'CA','Ventura',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91107,'CA','Pasadena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93445,'CA','Oceano',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90245,'CA','El Segundo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90706,'CA','Bellflower',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91006,'CA','Arcadia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93402,'CA','Los Osos',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91724,'CA','Covina',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92415,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93704,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92407,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92861,'CA','Villa Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92584,'CA','Menifee',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93728,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92677,'CA','Laguna Niguel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91761,'CA','Ontario',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93465,'CA','Templeton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92505,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92626,'CA','Costa Mesa',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90064,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93227,'CA','Goshen',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90501,'CA','Torrance',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90304,'CA','Inglewood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91390,'CA','Agua Dulce',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90049,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91351,'CA','Santa Clarita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91364,'CA','Woodland Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91321,'CA','Newhall',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90606,'CA','Whittier',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93442,'CA','Morro Bay',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93927,'CA','Greenfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93261,'CA','Richgrove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93441,'CA','Los Olivos',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95004,'CA','Aromas',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92602,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93539,'CA','Lancaster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93283,'CA','Weldon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92359,'CA','Mentone',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90042,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92240,'CA','Desert Hot Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93022,'CA','Oak View',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91040,'CA','Sunland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92553,'CA','Moreno Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91505,'CA','Burbank',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90254,'CA','Hermosa Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93451,'CA','San Miguel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91320,'CA','Newbury Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91402,'CA','Panorama City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92268,'CA','Pioneertown',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91342,'CA','Sylmar',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92586,'CA','Menifee',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91344,'CA','Granada Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91381,'CA','Stevenson Ranch',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92211,'CA','Palm Desert',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92372,'CA','Pinon Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90033,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93920,'CA','Big Sur',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92870,'CA','Placentia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92843,'CA','Garden Grove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92649,'CA','Huntington Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93923,'CA','Carmel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91767,'CA','Pomona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92675,'CA','San Juan Capistrano',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93552,'CA','Palmdale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93483,'CA','Grover Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93202,'CA','Armona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93244,'CA','Lemon Cove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92223,'CA','Cherry Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90241,'CA','Downey',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92203,'CA','Indio',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91741,'CA','Glendora',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93940,'CA','Monterey',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93428,'CA','Cambria',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92780,'CA','Tustin',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95043,'CA','Paicines',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90067,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92629,'CA','Dana Point',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95012,'CA','Castroville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93453,'CA','Santa Margarita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91331,'CA','Arleta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93513,'CA','Big Pine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91406,'CA','Van Nuys',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93066,'CA','Somis',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93627,'CA','Helm',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90703,'CA','Cerritos',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92867,'CA','Villa Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90717,'CA','Lomita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92253,'CA','La Quinta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93601,'CA','Ahwahnee',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93216,'CA','Delano',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92614,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91321,'CA','Santa Clarita',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92835,'CA','Fullerton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90058,'CA','Vernon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91367,'CA','Woodland Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92585,'CA','Menifee',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93606,'CA','Biola',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91303,'CA','Canoga Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93117,'CA','Gaviota',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90021,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92672,'CA','San Clemente',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90034,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93240,'CA','Lake Isabella',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91784,'CA','Upland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91325,'CA','Northridge',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90712,'CA','Lakewood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93720,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91733,'CA','South El Monte',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93450,'CA','San Ardo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91204,'CA','Glendale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90631,'CA','La Habra Heights',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92270,'CA','Rancho Mirage',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92882,'CA','Corona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93007,'CA','Ventura',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93604,'CA','Bass Lake',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92344,'CA','Hesperia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92397,'CA','Wrightwood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90272,'CA','Pacific Palisades',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91326,'CA','Porter Ranch',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92395,'CA','Victorville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93447,'CA','Paso Robles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93258,'CA','Porterville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90640,'CA','Montebello',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92833,'CA','Fullerton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90240,'CA','Downey',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90274,'CA','Rolling Hills Estate',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92352,'CA','Lake Arrowhead',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93449,'CA','Pismo Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93638,'CA','Madera',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90249,'CA','Gardena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92647,'CA','Huntington Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91744,'CA','La Puente',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92564,'CA','Murrieta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90277,'CA','Redondo Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90502,'CA','Torrance',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93012,'CA','Camarillo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93721,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92320,'CA','Calimesa',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91606,'CA','North Hollywood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92625,'CA','Corona Del Mar',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91106,'CA','Pasadena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90505,'CA','Torrance',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90802,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92532,'CA','Lake Elsinore',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90250,'CA','Hawthorne',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92508,'CA','Riverside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92841,'CA','Garden Grove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91706,'CA','Irwindale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92802,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93648,'CA','Parlier',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93201,'CA','Alpaugh',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91307,'CA','Bell Canyon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93510,'CA','Acton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92536,'CA','Aguanga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92356,'CA','Lucerne Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92678,'CA','Trabuco Canyon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90746,'CA','Carson',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91739,'CA','Rancho Cucamonga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90670,'CA','Santa Fe Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90023,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92248,'CA','La Quinta',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90201,'CA','Bell Gardens',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90018,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90805,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90403,'CA','Santa Monica',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92276,'CA','Thousand Palms',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92408,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93701,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90260,'CA','Lawndale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93108,'CA','Montecito',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93406,'CA','San Luis Obispo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92543,'CA','Hemet',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90248,'CA','Gardena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91708,'CA','Chino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91335,'CA','Reseda',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91790,'CA','West Covina',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91354,'CA','Valencia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91732,'CA','El Monte',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92807,'CA','Anaheim Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92226,'CA','Blythe',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91040,'CA','Shadow Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90806,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91406,'CA','Lake Balboa',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90745,'CA','Carson',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92624,'CA','Capistrano Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93020,'CA','Moorpark',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95039,'CA','Moss Landing',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92615,'CA','Huntington Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91311,'CA','Chatsworth',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91384,'CA','Castaic',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93421,'CA','Arroyo Grande',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90713,'CA','Lakewood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92252,'CA','Joshua Tree',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92735,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93581,'CA','Tehachapi',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92385,'CA','Skyforest',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90710,'CA','Harbor City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91201,'CA','Glendale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93502,'CA','Mojave',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91752,'CA','Jurupa Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92310,'CA','Fort Irwin',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93639,'CA','Madera',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92586,'CA','Sun City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93651,'CA','Prather',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93390,'CA','Bakersfield',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92607,'CA','Laguna Niguel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92866,'CA','Orange',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90815,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93279,'CA','Visalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93238,'CA','Kernville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92549,'CA','Idyllwild',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93550,'CA','Palmdale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93219,'CA','Earlimart',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93602,'CA','Auberry',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93664,'CA','Shaver Lake',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90701,'CA','Artesia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91316,'CA','Encino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93637,'CA','Berenda',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92220,'CA','Banning',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91221,'CA','Glendale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93907,'CA','Prunedale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91104,'CA','Pasadena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92728,'CA','Fountain Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93591,'CA','Palmdale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93041,'CA','Port Hueneme',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93667,'CA','Tollhouse',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91343,'CA','North Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91711,'CA','Claremont',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92683,'CA','Westminster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92591,'CA','Temecula',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93921,'CA','Carmel',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92654,'CA','Laguna Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90046,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93709,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93440,'CA','Los Alamos',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91763,'CA','Montclair',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93255,'CA','Onyx',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92285,'CA','Landers',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92539,'CA','Anza',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93675,'CA','Squaw Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93518,'CA','Caliente',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92604,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93555,'CA','Ridgecrest',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93205,'CA','Bodfish',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92612,'CA','Irvine',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90602,'CA','Whittier',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92202,'CA','Indio',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (95024,'CA','Hollister',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92344,'CA','Oak Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93644,'CA','Oakhurst',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93455,'CA','Orcutt',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90212,'CA','Beverly Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93403,'CA','San Luis Obispo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90026,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92567,'CA','Nuevo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93536,'CA','Lancaster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91362,'CA','Westlake Village',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93950,'CA','Pacific Grove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92691,'CA','Mission Viejo',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90071,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92585,'CA','Romoland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90732,'CA','San Pedro',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93012,'CA','Santa Rosa Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93925,'CA','Chualar',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90274,'CA','Rolling Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91766,'CA','Phillips Ranch',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91353,'CA','Sun Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93531,'CA','Keene',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92375,'CA','Redlands',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92264,'CA','Palm Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91342,'CA','Lake View Terrace',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92258,'CA','North Palm Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93543,'CA','Littlerock',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92392,'CA','Victorville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91745,'CA','Hacienda Heights',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93726,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90503,'CA','Torrance',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93249,'CA','Lost Hills',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90504,'CA','Torrance',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93647,'CA','Orosi',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91042,'CA','Tujunga',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90017,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92676,'CA','Silverado',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92342,'CA','Helendale',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93427,'CA','Buellton',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91351,'CA','Canyon Country',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92842,'CA','Garden Grove',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90715,'CA','Lakewood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93103,'CA','Santa Barbara',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90402,'CA','Santa Monica',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92707,'CA','Santa Ana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92256,'CA','Morongo Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93560,'CA','Rosamond',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90265,'CA','Malibu',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92336,'CA','Fontana',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93286,'CA','Woodlake',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92339,'CA','Forest Falls',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93702,'CA','Fresno',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93524,'CA','Edwards',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93562,'CA','Trona',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92661,'CA','Newport Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91306,'CA','Winnetka',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93243,'CA','Lebec',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92423,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90803,'CA','Long Beach',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92679,'CA','Trabuco Canyon',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93429,'CA','Casmalia',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92694,'CA','Ladera Ranch',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90046,'CA','West Hollywood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92548,'CA','Homeland',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92509,'CA','Jurupa Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90048,'CA','West Hollywood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92314,'CA','Big Bear City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91320,'CA','Thousand Oaks',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93584,'CA','Lancaster',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91401,'CA','Van Nuys',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91030,'CA','South Pasadena',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92804,'CA','Anaheim',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90069,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90255,'CA','Huntington Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90230,'CA','Culver City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91789,'CA','Walnut',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90604,'CA','Whittier',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93430,'CA','Cayucos',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90621,'CA','Buena Park',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90275,'CA','Rancho Palos Verdes',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92277,'CA','Twentynine Palms',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93464,'CA','Solvang',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92557,'CA','Moreno Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92551,'CA','Moreno Valley',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93643,'CA','North Fork',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93265,'CA','Springville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92241,'CA','Desert Hot Springs',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93932,'CA','Lockwood',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92234,'CA','Cathedral City',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (90044,'CA','Los Angeles',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93271,'CA','Three Rivers',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (93955,'CA','Seaside',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92393,'CA','Victorville',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (92410,'CA','San Bernardino',NOW());
INSERT INTO ZipCodes(ZipCodeID,StateID,City,Time_Stamp) VALUES (91791,'CA','West Covina',NOW());
*/